Makefile
=> Docs: Makefile 작성

Makefile, srcs/main.c, srcs/signal.c
=> Feat. main분리

.gitignore, Makefile, includes/minishell.h, srcs/exec_builtin.c, srcs/exec_cmd.c, srcs/ft_free.c, srcs/main.c, srcs/parsing.c
1. builtin 명령어와 그 외 명령어를 구분하여 실행하는 컨트롤러 구현
2. cmds 구조체 변경
cmds->cmd를 2차원 배열로 변경
3. gitignore 변경
=> Feat: 명령 컨트롤러 구현

srcs/main.c
1. add_history main에 추가
resolved #9
=> Feat: 작업히스토리 기능 구현

includes/minishell.h, srcs/parsing.c, srcs/parsing_utils.c, srcs/redirection.c, srcs/redirection_utils.c, srcs/redirection_utils2.c, srcs/test.c
1. 미니쉘 모드에 리다이렉션 기능 추가
resolved #10
=> Feat: 리다이렉션 기능 추가

Makefile, includes/minishell.h, srcs/exec_another.c, srcs/exec_cmd.c, srcs/exec_utils.c, srcs/ft_free.c, srcs/main.c, srcs/parsing.c, srcs/parsing_utils.c, srcs/test.c
1. 내부 커맨드 실행을 위한 exec_another 함수 구현
2. fork 하여 excute 작업을 하는 frist_process 함수 구현
resolved #29
=> Feat: 내부 커맨드 실행 기능 구현

includes/minishell.h, srcs/exec_another.c, srcs/exec_cmd.c
1. 미니쉘 모드에 파이프 기능 추가
resolved #11
=> Feat: 파이프 기능 구현

Makefile, includes/minishell.h, srcs/builtin_cmd.c, srcs/builtin_utils.c, srcs/check_pipe.c, srcs/check_readline.c, srcs/check_redir.c, srcs/error_handling.c, srcs/exec_another.c, srcs/exec_cmd.c, srcs/exec_utils.c, srcs/main.c, srcs/parsing.c, srcs/parsing_utils.c, srcs/parsing_utils2.c, srcs/redirection_utils.c, srcs/redirection_utils2.c, srcs/test.c
1. 파이프 함수 실패에 대한 예외처리 구현
2. fork 함수 실패에 대한 예외처리 구현
3. 파싱에 대한 에러처리 구현 (syntax error)
4. 에러메시지 함수화 (error_handling.c)
resolve #36
=> Feat: 에러처리 구현

includes/minishell.h, srcs/exec_builtin.c, srcs/exec_cmd.c, srcs/parsing.c
1. 파이프 기능 추가
2. 리다이렉션 기능 추가
3. fork 함수를 이용한 자식 프로세스 처리 구현
resolved #39
=> Feat: 빌트인 함수 실행 기능 구현

srcs/parsing_utils2.c, srcs/test.c
1. make_cmd_pipe 함수 로직 수정 (split 방식->인덱스 방식)
resolved #38
=> Fix: syntax 에러처리 비정상 작동 수정

includes/minishell.h, srcs/exec_another.c, srcs/exec_cmd.c, srcs/parsing.c, srcs/redirection.c, srcs/redirection_utils2.c
1. here_doc 리다이렉션을 여러개 넣을 경우, 정상적으로 작동하지 않는 현상 수정
resolved #46
=> Fix: here_doc 리다이렉션 비정상 작동 수정

srcs/exec_cmd.c
1. 파이프 기능이 정상적으로 작동하지 않는 현상 수정
resolved #50
=> Fix: 파이프 기능이 정상적으로 작동하지 않는 현상 수정

includes/builtin_cmd.h, includes/minishell.h, srcs/builtin_cmd.c, srcs/builtin_cmd2.c, srcs/exec_builtin.c, srcs/exec_cmd.c
1. 단일 명령어로 빌트인 함수가 들어올 경우 부모프로세스에서 처리되도록 수정
resolved #42
=> Fix: exit 빌트인 함수가 정상적으로 처리되지 않는 현상 수정

srcs/exec_builtin.c
1. exec_builtin에 있던 주석 제거
resolve #56
=> Bug: unset 명령어 작동 추가

includes/builtin_cmd.h, srcs/builtin_cmd.c, srcs/exec_builtin.c
1.cd만 입력되거나 ~가 입력된경우 홈디렉토리경로를 환경변수에서 참조하여 이동하는 것으로 변경
resolve #53
=> Fix: cd 빌트인 함수 수정

includes/builtin_cmd.h, includes/minishell.h, srcs/builtin_cmd.c, srcs/exec_builtin.c
1. 파이프라인에서 exit 빌트인 오류 발생시, exit를 출력하지 않도록 수정
resolved #54
=> Fix: exit 빌트인 함수 오류 수정

Makefile, includes/builtin_cmd.h, includes/minishell.h, srcs/builtin_cmd.c, srcs/exec_builtin.c, srcs/parsing.c, srcs/parsing_utils4.c
1. $다음으로 오는 값들에 대해 환경변수로 확장되는 기능 추가
resolved #15
=> FEAT: 환경변수 기능추가

Makefile, includes/minishell.h, srcs/exec_another.c, srcs/exec_builtin.c, srcs/exec_cmd.c, srcs/main.c, srcs/parsing.c, srcs/parsing_utils5.c, srcs/redirection.c, srcs/redirection_utils2.c
1. heredoc 병렬처리 하지 않고 부모프로세스에서 한번에 실행
2. 이후 cmd 값을 <, heredoc 으로 변환하여 임시파일에 리다이렉션 되도록 수정
resolved #73
=> Fix: heredoc 병렬처리 안하도록 수정

includes/minishell.h, srcs/exec_another.c, srcs/exec_cmd.c, srcs/parsing_utils4.c
1. pipe status 처리
resolved #72
=> Feat: pipe status 처리

Makefile, includes/minishell.h, srcs/exec_another.c, srcs/exec_builtin.c, srcs/exec_cmd.c, srcs/exec_utils.c, srcs/execute_cmd.c, srcs/wait_status.c
1. 자식 프로세스에 대한 wait을 나중에 하여 병렬처리가 정상적으로 될 수 있도록 로직 수정
2. 자식 프로세스가 signal에 의해 종료 되었을 경우 해당 시그널 종료코드를 반환할수 있도록 코드 추가
3. 해당 기능에 대한 함수 및 파일 정리
resolved #80
=> Feat: pipe 병렬처리 기능 수정

srcs/parsing_utils4.c
1. ${PIPESTATUS}값 확장기능 추가
resolved #issue77
=> Feat: echo 기능추가

includes/minishell.h, srcs/parsing.c, srcs/parsing_utils.c
1. 단일 파이프가 왔을 경우 정상적으로 에러가 처리 되도록 수정
resolved #85
=> Fix: syntax 에러처리 오류 수정

includes/minishell.h, srcs/parsing_utils.c
1. 파이프라인 이후 사용자 입력에서 eof 전달시 segment falt 오류 수정
2. syntax 에러출력 문이 개행으로 출력되어 해당 현상 수정 필요
resolved #84
=> Fix: segment falt 오류 수정

includes/minishell.h, srcs/parsing_utils.c, srcs/redirection.c, srcs/redirection_utils2.c
1. here doc 모드에서 eof 입력시 segment falut 현상 수정
resolved #87
=>  Fix: segment falut 오류 수정

srcs/builtin_cmd2.c, srcs/ft_free.c
1. export, unset 명령어 이후 memory leaks 발생 수정
2. free_arr 수정
resolved #92
=> Fix: export, unset 명령어 이후 memory leaks 발생

includes/builtin_cmd.h, srcs/builtin_cmd.c, srcs/exec_builtin.c
1. echo 입력시 segment falt 현상 수정
resolved #83
=> Fix: echo 입력시 segment falt 현상 수정

Makefile, includes/minishell.h, srcs/exec_cmd.c, srcs/exec_cmd_utils.c, srcs/main.c, srcs/parsing.c, srcs/parsing_utils.c, srcs/parsing_utils3.c, srcs/redirection.c, srcs/setting.c
1. stdin에서 eof시 새로운 프롬프트로 넘어갈수있도록 구현
resolved #81
=> Fix: signal 처리 함수 변경

srcs/parsing.c, srcs/parsing_utils3.c
1. last cmd 추가 때 eof 보낼 경우 오류 수정
resolved #106
=> Fix: last cmd 추가 시 eof 보낼경우 오류 수정

srcs/main.c
1. 환경 변수 관련 메모리 누수 방지
resolved #108
=> Fix: 메모리 누수 해결

includes/minishell.h, srcs/cursor.c, srcs/main.c, srcs/parsing_utils3.c, srcs/redirection.c, srcs/setting.c
1. 스크린 끝에서 readline을 받는 경우와, 중간에서 받는 경우를 분리해서 처리하는 기능 추가.
=> Feat: 커서변경기능 추가

Makefile, includes/minishell.h, srcs/execute/exec_cmd.c, srcs/main.c, srcs/parsing/parsing.c, srcs/parsing/parsing_utils2.c, srcs/parsing/parsing_utils5.c, srcs/parsing/t_cmds_utils.c, srcs/redirection/redirection.c, srcs/syntax/check_readline.c, srcs/utils/ft_free.c, srcs/utils/make_temp_file.c
1. 기존의 동일한 이름의 임시파일이 있을 경우 다른 이름으로 임시파일 생성하도록 구현
resolved #127
=> Feat: heredoc 임시파일 이름 변경 로직 구현

srcs/execute/builtin/builtin_cmd.c, srcs/execute/exec_cmd.c, srcs/main.c
1. 빈명령어 이후 히스토리 접근 시 세그먼트 폴트 현상 해결
2. c 명령어 입력시 에러처리 정상적으로 작동하도록 수정
3. pwd 명령어 메모리 누수 문제 해결
resolved #131
=> Fix: 발생한 버그 수정

Makefile, includes/minishell.h, srcs/parsing/change_cmd_with_list.c, srcs/parsing/change_cmd_with_list1.c, srcs/parsing/parsing.c, srcs/parsing/t_cmds_utils.c
1. $?의 경우, exit status가 들어오게끔 추가
2. 쌍따옴표안의 띄어쓰기 오류는 cmd가 2차원 배열이 되기전 parsing과정을 추가해서 오류가 나지않도록 변경
resolved #134, #135
=> Feat: tokenizing 기능 추가

srcs/main.c, srcs/setting/setting.c, srcs/setting/signal.c
1.시그널 입력이 화면에 표시되도록 기능변경
resolve #137
=> Fix: 명령어 실행중 시그널입력처리

Makefile, srcs/parsing/parsing.c, srcs/parsing/parsing_utils.c, srcs/redirection/redirection.c, srcs/redirection/redirection_utils.c
1. in redir 수정
2. heredoc 수정
resolved #145
=> Fix: redirection 오류 수정

Makefile, srcs/execute/exec_cmd_utils.c, srcs/parsing/parsing.c
1. syntax 오류 처리 부분 메모리 누수 해결
resolved #146
=> Fix: syntax 오류 처리 부분 메모리 누수 해결

srcs/parsing/parsing_utils.c
=> Fix: 명령어 파싱오류

srcs/parsing/parsing_utils3.c
1. add에 널문자열이 오는경우 처리
resolved #154
=> Bug: 세그먼트 오류 해결

includes/minishell.h, srcs/execute/exec_cmd.c, srcs/execute/exec_utils.c
1. heredoc 시그널 종료시 임시파일 제거
resolved #160
=> Feat: heredoc 시그널 종료시 임시파일 제거

Makefile, includes/minishell.h, srcs/parsing/change_cmd_with_list.c, srcs/parsing/change_cmd_with_list1.c, srcs/parsing/change_cmd_with_list2.c, srcs/setting/cursor.c, srcs/setting/terminal.c
1.함수 길이를 제외한 norm양식
resolved #164
=> Docs: norm

srcs/execute/builtin/builtin_cmd2.c
1. 인자로 들어온 이름의 환경변수가 없을경우, 환경변수 리스트를 프리하는 오류 발생
2. ft_free를 if문 안에 넣어서 해결
resolved #179
=> Bug: unset오류

Makefile, includes/minishell.h, includes/struct.h, includes/tokenizing.h, srcs/main.c, srcs/tokenize/divide_line.c
=> Feat: tokenize하여 이차원배열로 반환 하는 함수추가

Makefile, includes/tokenize.h, srcs/parsing/parsing.c, srcs/tokenize/create_divide_redir.c, srcs/tokenize/divide_redir.c
1. tokenize 배열 요소중 리다이렉션이 붙어 있는 경우 분리하는 기능 추가
resolved #184
=> Feat: tokenize 배열 요소 정리 기능 추가

Makefile, srcs/tokenize/interpret_cmd.c, srcs/tokenize/interpret_dollar.c
=> Feat : 따옴표제거 및 환경변수 해석

srcs/parsing/parsing_utils3.c, srcs/tokenize/set_cmd.c
1. 미니쉘 히스토리 라인 오류 수정
resovled #175
=> Fix: 미니쉘 히스토리 라인 오류 수정

Makefile, srcs/parsing/parsing.c, srcs/tokenize/divide_arr.c, srcs/tokenize/set_cmd.c
1. 리스트 생성시 next 값이 초기화가 안되어 있었음
2. 명령 프롬프트에 탭 입력시 segmentfalut 발생하는 현상도 수정
resolved #193
=> Fix: 간헐적으로 명령어 입력시 segmentfalut 오류 수정

includes/tokenizing.h, srcs/tokenize/interpret_cmd.c, srcs/tokenize/interpret_dollar.c
1. no quote 경우 $를 환경변수로 변환
resolved #196
=> Fix: No quote 경우도 $를 환경변수로 대체
